In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

In [8]:
df = pd.read_csv("data/train_data.csv")
df

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,sqft_above,sqft_basement,yr_renovated,lat,long,hous_val_amt,trend,trend_sq,house_age,was_renovated
0,7129300520,2014-10-13,221900.0,3,1,1180,5650,1.0,0,0,...,1180,0,0,47.5112,-122.257,175400.0,5,25,59,False
1,6414100192,2014-12-09,538000.0,3,2,2570,7242,2.0,0,0,...,2170,400,1991,47.7210,-122.319,225900.0,7,49,63,True
2,5631500400,2015-02-25,180000.0,2,1,770,10000,1.0,0,0,...,770,0,0,47.7379,-122.233,246600.0,9,81,82,False
3,2487200875,2014-12-09,604000.0,4,3,1960,5000,1.0,0,0,...,1050,910,0,47.5208,-122.393,280200.0,7,49,49,False
4,1954400510,2015-02-18,510000.0,3,2,1680,8080,1.0,0,0,...,1680,0,0,47.6168,-122.045,239850.0,9,81,28,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18559,263000018,2014-05-21,360000.0,3,2,1530,1131,3.0,0,0,...,1530,0,0,47.6993,-122.346,279200.0,0,0,5,False
18560,6600060120,2015-02-23,400000.0,4,2,2310,5813,2.0,0,0,...,2310,0,0,47.5107,-122.362,180100.0,9,81,1,False
18561,1523300141,2014-06-23,402101.0,2,1,1020,1350,2.0,0,0,...,1020,0,0,47.5944,-122.299,219400.0,1,1,5,False
18562,291310100,2015-01-16,400000.0,3,2,1600,2388,2.0,0,0,...,1600,0,0,47.5345,-122.069,308700.0,8,64,11,False
18563,1523300157,2014-10-15,325000.0,2,1,1020,1076,2.0,0,0,...,1020,0,0,47.5941,-122.299,219400.0,5,25,6,False

In [6]:
def KNN_felipe(t_data, variables, sample, neighborhood): 
    usable_data = t_data[variables].copy()
    usable_sample = sample[variables].copy()
    
    sqr_subtraction = (usable_data - usable_sample)**2
    
    # usable_data["sqr_subtraction"] = [sqr_subtraction.iloc[i].sum() for i in sqr_subtraction.index] - cálculo abandonado por conta de demora de execução 
    usable_data["sqr_subtraction"] = sqr_subtraction.sum(axis=1) # - versão vetorizada 
    usable_data["subtraction"] = usable_data["sqr_subtraction"]**0.5
    usable_data["price"] = t_data["price"]
    usable_data.sort_values(by = "subtraction", inplace = True)
    usable_data.reset_index(inplace = True, drop = True)

    

    estimated_price = usable_data.loc[0:neighborhood -1, "price"].mean()
    

    return(estimated_price)

In [9]:
first_price = KNN_felipe(df, variables_1, test, 20)
first_price

907025.0

In [12]:
variables_1 = ["bedrooms", "bathrooms", "sqft_living", "sqft_lot", "floors", "sqft_above", "lat", "long", "house_age"]

In [25]:
test_set = pd.read_csv("data/test_data.csv")
#test = test_set.loc[1,["bedrooms", "bathrooms", "sqft_living", "sqft_lot", "floors", "sqft_above", "lat", "long", "house_age"]]
dict = {c: 0 for c in variables_1}

for i in variables_1:
    dict[i] = dict[i]+test_set.loc[2,i]

dict

{'bedrooms': 3,
 'bathrooms': 1,
 'sqft_living': 1250,
 'sqft_lot': 9774,
 'floors': 1.0,
 'sqft_above': 1250,
 'lat': 47.3343,
 'long': -122.306,
 'house_age': 46}

In [24]:
test

bedrooms             3
bathrooms            2
sqft_living       3560
sqft_lot          9796
floors             1.0
sqft_above        1860
lat            47.6007
long          -122.145
house_age           50
Name: 1, dtype: object

In [19]:
set_treino = df.loc[:,["bedrooms", "bathrooms", "sqft_living", "sqft_lot"]]
set_treino

       bedrooms  bathrooms  sqft_living  sqft_lot
0             3          1         1180      5650
1             3          2         2570      7242
2             2          1          770     10000
3             4          3         1960      5000
4             3          2         1680      8080
...         ...        ...          ...       ...
18559         3          2         1530      1131
18560         4          2         2310      5813
18561         2          1         1020      1350
18562         3          2         1600      2388
18563         2          1         1020      1076

[18564 rows x 4 columns]

In [18]:
(set_treino - test)**2

      bedrooms bathrooms sqft_living  sqft_lot
0            0         1     5664400  17189316
1            0         0      980100   6522916
2            1         1     7784100     41616
3            1         1     2560000  23001616
4            0         0     3534400   2944656
...        ...       ...         ...       ...
18559        0         0     4120900  75082225
18560        1         0     1562500  15864289
18561        1         1     6451600  71334916
18562        0         0     3841600  54878464
18563        1         1     6451600  76038400

[18564 rows x 4 columns]

In [ ]:
test_set.iloc

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,sqft_above,sqft_basement,yr_renovated,lat,long,hous_val_amt,trend,trend_sq,house_age,was_renovated
0,2414600126,2015-04-15,229500.0,3,1,1780,7470,1.0,0,0,...,1050,730,0,47.5123,-122.337,180100.0,11,121,55,False
1,1736800520,2015-04-03,662500.0,3,2,3560,9796,1.0,0,0,...,1860,1700,0,47.6007,-122.145,252600.0,11,121,50,False
2,7983200060,2015-04-24,230000.0,3,1,1250,9774,1.0,0,0,...,1250,0,0,47.3343,-122.306,166800.0,11,121,46,False
3,2799800710,2015-04-07,301000.0,3,2,2420,4750,2.0,0,0,...,2420,0,0,47.3663,-122.122,192000.0,11,121,12,False
4,2391600320,2015-04-20,480000.0,3,1,1040,5060,1.0,0,0,...,1040,0,0,47.5636,-122.394,286600.0,11,121,74,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2080,2122059216,2015-04-14,422000.0,4,2,2930,5973,2.0,0,0,...,2930,0,0,47.3846,-122.186,239850.0,11,121,7,False
2081,3528900770,2015-04-23,710200.0,4,3,1670,2642,2.0,0,0,...,1350,320,0,47.6397,-122.345,433500.0,11,121,7,False
2082,1931300412,2015-04-16,475000.0,3,2,1190,1200,3.0,0,0,...,1190,0,0,47.6542,-122.346,279200.0,11,121,7,False
2083,191100405,2015-04-21,1575000.0,4,3,3410,10125,2.0,0,0,...,3410,0,0,47.5653,-122.223,573900.0,11,121,8,False
2084,5100403806,2015-04-07,467000.0,3,2,1425,1179,3.0,0,0,...,1425,0,0,47.6963,-122.318,225900.0,11,121,7,False

In [ ]:
from fastapi import FastAPI
from pydantic import BaseModel
import pandas as pd

from KNN_teste import KNN_felipe

app = FastAPI()

# carregar dataset apenas uma vez
dataset = pd.read_csv("data/train_data.csv")
variables =  ["bedrooms", "bathrooms", "sqft_living", "sqft_lot", "floors", "sqft_above", "lat", "long", "house_age"]
K = 5


class House(BaseModel):

    sqft_living: float
    bedrooms: int
    bathrooms: float
    sqft_lot: float
    floors: int
    sqft_above: int
    lat: float
    long: float
    house_age: int


@app.post("/predict")
def predict(data: House):

    sample = data.model_dump()

    sample_df = pd.DataFrame([sample])

    price = KNN_felipe(
        t_data=dataset,
        variables=variables,
        sample=sample_df,
        neighborhood=K
    )

    return {"predicted_price": price}